---
#
# Ansible managed
#
repository:
  description: Install and configure xinetd on your system.
  homepage: https://robertdebock.nl/
  topics: daemon, installer, networking, system, xinetd, ansible, molecule, tox, playbook
