---
# tasks file for ansible-role-xinetd
- name: install software
  package:
    name: xinetd
    state: latest

- name: start and enable software
  service:
    name: xinetd
    state: started
    enabled: yes
