---
# tasks file for xinetd
- name: install software
  package:
    name: xinetd
    state: present
  register: xinetd_install_software
  until: xinetd_install_software is succeeded
  retries: 3

- name: start and enable software
  service:
    name: xinetd
    state: started
    enabled: yes
