---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: xinetd-opensuse-42.2
    image: opensuse:42.2
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: opensuse-42.2
verifier:
  name: goss
  lint:
    name: yamllint
