---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: xinetd-opensuse-tumbleweed
    image: opensuse:tumbleweed
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        xinetd_ignore_docker: no
  lint:
    name: ansible-lint
scenario:
  name: opensuse-tumbleweed
verifier:
  name: goss
  lint:
    name: yamllint
