---
#
# Ansible managed
#

name: Release to Ansible Galaxy

on:
  push:
    tags:
      - '*'
  schedule:
    - cron: '25 22 24 * *'

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: galaxy
        uses: robertdebock/galaxy-action@1.1.0
        with:
          galaxy_api_key: ${{ secrets.galaxy_api_key }}
